services:
  - type: web
    name: multidependencias-web
    env: docker
    region: ohio # Option: oregon, frankfurt, singapore
    plan: free
    branch: main
    envVars:
      - key: APP_NAME
        value: "MultiDependencias"
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        value: "base64:ycyr55+UuvcrlqXFopyytDAURuxbzy5DUzi/ar1epRw="
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: "https://drsofts.com"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: "mysql-2b2a491b-errami167-ff86.d.aivencloud.com" 
      - key: DB_PORT
        value: "19962" 
      - key: DB_DATABASE
        value: "defaultdb"
      - key: DB_USERNAME
        value: "avnadmin"
      - key: DB_PASSWORD
        sync: false
      # Limpieza de caché automáticas de Laravel
      - key: BROADCAS_DRIVER
        value: "log"
      - key: CACHE_DRIVER
        value: "database"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: SESSION_DRIVER
        value: "database"
      - key: SESSION_LIFETIME
        value: "120"
